# ByteTrack configuration
max_age: 30          # Increase from 1 to 30 for better track persistence
min_hits: 3          # Keep at 3 for reasonable track initialization
iou_threshold: 0.3   # Keep at 0.3 for good matching
low_thresh: 0.05     # Lower the low detection confidence threshold
high_thresh: 0.3     # Lower the high detection confidence threshold
yolo_model: 'yolov8n.pt'  # Add YOLOv8 model specification